### ISSUE TITLE
Crée des prototypes pour chaque page

### ISSUE THREAD

**Issue by Arthur-Melchior** [Arthur-Melchior/404-Module306#3]

**Comment by t0smo** [comment]
![Image](https://github.com/Arthur-Melchior/404-Module306/assets/118718098/7e98f727-91c0-4adf-ac72-e90471ff6418)
![Image](https://github.com/Arthur-Melchior/404-Module306/assets/118718098/9f0840b6-824c-4ffe-981f-e7ab218fb09b)
![Image](https://github.com/Arthur-Melchior/404-Module306/assets/118718098/0bebb657-3be8-4446-8c47-e9d04d0ca54d)
